#!/usr/bin/env bash
DOTFILES_REPO_URL="${DOTFILES_REPO_URL:-https://github.com/commandglows/dotfiles.git}"
DOTFILES_BRANCH="${DOTFILES_BRANCH:-master}"
DOTFILES_DIR="${DOTFILES_DIR:-$HOME/.dotfiles}"
DOTFILES_STATE_DIR="${DOTFILES_STATE_DIR:-${XDG_STATE_HOME:-$HOME/.local/state}/dotfiles}"
DOTFILES_MANIFEST="${DOTFILES_MANIFEST:-$DOTFILES_DIR/dotfiles/components.tsv}"
DOTFILES_JOURNAL="${DOTFILES_JOURNAL:-$DOTFILES_STATE_DIR/journal.tsv}"
DOTFILES_DRY_RUN=false
DOTFILES_CHECK=false
DOTFILES_UPDATE=false
DOTFILES_UNINSTALL=false
DOTFILES_ONLY=""
