# Termux Properties
# Rechargement: termux-reload-settings

# Masquer la barre de touches supplémentaires (extra keys)
extra-keys = [[]]

# Plein écran (masque barre de statut et navigation Android)
fullscreen = true
use-fullscreen-workaround = true

# Thème sombre forcé
use-black-ui = true
night-mode = true

# Style du curseur
terminal-cursor-style = underline

# Désactiver le toast lors du changement de session
disable-terminal-session-change-toast = true

# Ouvrir les URLs cliquées dans le terminal
terminal-onclick-url-open = true
