import stylistic from "@stylistic/eslint-plugin"

export const fmRules = {
	// Layout & Formatting (now via @stylistic)
	"@stylistic/array-bracket-newline"         : ["warn", "consistent"],
	"@stylistic/array-bracket-spacing"         : "warn",
	"@stylistic/array-element-newline"         : ["warn", "consistent"],
	"@stylistic/arrow-parens"                  : ["warn", "as-needed"],
	"@stylistic/arrow-spacing"                 : "warn",
	"@stylistic/block-spacing"                 : "warn",
	"@stylistic/brace-style"                   : ["warn", "1tbs", { allowSingleLine: true }],
	"@stylistic/comma-dangle"                  : ["warn", "always-multiline"],
	"@stylistic/comma-spacing"                 : "warn",
	"@stylistic/comma-style"                   : "warn",
	"@stylistic/computed-property-spacing"     : "warn",
	"@stylistic/dot-location"                  : ["warn", "property"],
	"@stylistic/eol-last"                      : "warn",
	"@stylistic/func-call-spacing"             : "warn",
	"@stylistic/function-call-argument-newline": ["warn", "consistent"],
	"@stylistic/function-paren-newline"        : "off",
	"@stylistic/generator-star-spacing"        : ["warn", { before: false, after: true }],
	"@stylistic/implicit-arrow-linebreak"      : "off",
	"@stylistic/indent"                        : ["warn", "tab", {
		VariableDeclarator      : "first",
		FunctionDeclaration     : { parameters: "first" },
		FunctionExpression      : { parameters: "first" },
		CallExpression          : { arguments: "first" },
		ArrayExpression         : "first",
		ObjectExpression        : "first",
		ImportDeclaration       : "first",
		flatTernaryExpressions  : true,
		offsetTernaryExpressions: true,
	}],
	"@stylistic/jsx-quotes"                 : "warn",
	"@stylistic/key-spacing"                : ["warn", { align: "colon" }],
	"@stylistic/keyword-spacing"            : "warn",
	"@stylistic/line-comment-position"      : "off",
	"@stylistic/linebreak-style"            : "warn",
	"@stylistic/lines-around-comment"       : "off",
	"@stylistic/lines-between-class-members": ["warn", "never"],
	"@stylistic/max-len"                    : ["warn", { code: 999, tabWidth: 2 }],
	"@stylistic/max-statements-per-line"    : "warn",
	"@stylistic/multiline-ternary"          : ["warn", "always-multiline"],
	"@stylistic/new-parens"                 : "warn",
	"@stylistic/newline-per-chained-call"   : "off",
	"@stylistic/no-extra-parens"            : "warn",
	"@stylistic/no-mixed-spaces-and-tabs"   : ["warn", "smart-tabs"],
	"@stylistic/no-multi-spaces"            : ["warn", {
		ignoreEOLComments: true,
		exceptions       : { Property: true, VariableDeclarator: true, ImportDeclaration: true },
	}],
	"@stylistic/no-multiple-empty-lines"         : ["warn", { max: 1, maxBOF: 0, maxEOF: 1 }],
	"@stylistic/no-tabs"                         : ["warn", { allowIndentationTabs: true }],
	"@stylistic/no-trailing-spaces"              : "warn",
	"@stylistic/no-whitespace-before-property"   : "warn",
	"@stylistic/nonblock-statement-body-position": ["warn", "any"],
	"@stylistic/object-curly-newline"            : "warn",
	"@stylistic/object-curly-spacing"            : ["warn", "always"],
	"@stylistic/object-property-newline"         : ["warn", { allowAllPropertiesOnSameLine: true }],
	"@stylistic/operator-linebreak"              : ["warn", "before"],
	"@stylistic/padded-blocks"                   : ["warn", "never"],
	"@stylistic/padding-line-between-statements" : [
		"warn",
		{ blankLine: "always", prev: "import", next: "*" },
		{ blankLine: "any", prev: "import", next: "import" },
		{ blankLine: "always", prev: "directive", next: "*" },
	],
	"@stylistic/quotes"                     : ["warn", "double", { avoidEscape: true, allowTemplateLiterals: true }],
	"@stylistic/rest-spread-spacing"        : "warn",
	"@stylistic/semi"                       : ["warn", "never", { beforeStatementContinuationChars: "never" }],
	"@stylistic/semi-spacing"               : "warn",
	"@stylistic/semi-style"                 : ["warn", "first"],
	"@stylistic/space-before-blocks"        : "warn",
	"@stylistic/space-before-function-paren": ["warn", {
		anonymous : "never",
		named     : "never",
		asyncArrow: "always",
	}],
	"@stylistic/space-in-parens"       : "warn",
	"@stylistic/space-infix-ops"       : "warn",
	"@stylistic/space-unary-ops"       : ["warn", { words: true, nonwords: false }],
	"@stylistic/switch-colon-spacing"  : "warn",
	"@stylistic/template-curly-spacing": "warn",
	"@stylistic/template-tag-spacing"  : "warn",
	"@stylistic/wrap-iife"             : ["warn", "outside", { functionPrototypeMethods: true }],
	"@stylistic/wrap-regex"            : "off",
	"@stylistic/yield-star-spacing"    : "warn",
	"@stylistic/member-delimiter-style": ["warn", {
		multiline : { delimiter: "none", requireLast: false },
		singleline: { delimiter: "comma", requireLast: false },
	}],
	"@stylistic/type-annotation-spacing": "warn",

	// Suggestions (still in core eslint)
	"arrow-body-style"              : "off",
	"capitalized-comments"          : "off",
	"curly"                         : "off",
	"dot-notation"                  : "warn",
	"eqeqeq"                        : "warn",
	"logical-assignment-operators"  : ["warn", "always", { enforceForIfStatements: true }],
	"multiline-comment-style"       : ["warn", "separate-lines", { checkJSDoc: true }],
	"no-confusing-arrow"            : ["warn", { onlyOneSimpleParam: true }],
	"no-div-regex"                  : "off",
	"no-else-return"                : "off",
	"no-empty"                      : ["warn", { allowEmptyCatch: true }],
	"no-extra-bind"                 : "warn",
	"no-extra-boolean-cast"         : ["warn", { enforceForLogicalOperands: true }],
	"no-extra-label"                : "warn",
	"no-floating-decimal"           : "warn",
	"no-implicit-coercion"          : ["warn", { boolean: false }],
	"no-lonely-if"                  : "warn",
	"no-undef-init"                 : "off",
	"no-unneeded-ternary"           : "warn",
	"no-useless-computed-key"       : ["warn", { enforceForClassMembers: true }],
	"no-useless-rename"             : "warn",
	"no-useless-return"             : "warn",
	"no-var"                        : "warn",
	"object-shorthand"              : "warn",
	"one-var-declaration-per-line"  : "warn",
	"operator-assignment"           : "warn",
	"prefer-arrow-callback"         : ["warn", { allowNamedFunctions: true }],
	"prefer-const"                  : ["warn", { destructuring: "all" }],
	"prefer-destructuring"          : "off",
	"prefer-exponentiation-operator": "warn",
	"prefer-numeric-literals"       : "off",
	"prefer-object-has-own"         : "off",
	"prefer-object-spread"          : "warn",
	"prefer-template"               : "warn",
	"quote-props"                   : ["warn", "consistent-as-needed"],
	"sort-imports"                  : ["warn", {
		ignoreCase           : true,
		ignoreDeclarationSort: true,
		allowSeparatedGroups : true,
	}],
	"sort-vars"     : ["warn", { ignoreCase: true }],
	"spaced-comment": ["warn", "always"],
	"strict"        : ["warn", "never"],
	"yoda"          : "warn",
}

/** @type { import('eslint').Linter.Config[] } */
export const formatting = [
	{
		files  : ["**/*.{ts,tsx,js,jsx,cjs,mjs,cts,mts}"],
		plugins: {
			"@stylistic": stylistic,
		},
		rules: fmRules,
	},
]
